### ISSUE TITLE
知识图谱只能考虑一阶的连通性吗？

### ISSUE THREAD

**Issue by HuaYZhao** [chenchongthu/JNSKR#2]
我在看代码时发现，n_entities的值为7197，该值为item的一阶连通实体总和。

这意味着知识图它无法考虑到二阶连通性吗？

**Comment by chenchongthu** [comment]
嗯，我们这篇文章里对问题进行了简化，目前是只考虑了图谱中的一阶关系。

**Comment by HuaYZhao** [comment]
感谢您的及时回复。另想问下，训练速度的大幅提升与这样简化假设《相关度》大吗

**Comment by chenchongthu** [comment]
会有一定的关系，但我认为相关度并不是很大。我觉得您可以尝试一下如KGAT等方法在不同阶关系下的训练效率，
也可以看一下我们其他关于高效非采样相关的文章。

**Comment by HuaYZhao** [comment]
好的，感谢你。
