### ISSUE TITLE
关于系数的计算

### ISSUE THREAD

**Issue by HuaYZhao** [chenchongthu/JNSKR#3]
在https://github.com/chenchongthu/JNSKR/blob/master/Model/utility/our_helper.py#L59这一行中
`ck[i] = c1 * np.power(m[i], p) / tem`
它是否应该是
`ck[i] = c1 * np.power(mk[i], p) / tem`

**Comment by chenchongthu** [comment]
感谢！我们刚才检查了一下，确实应该是ck[i] = c1 * np.power(mk[i], p) / tem ！不过对结果影响甚微😆，我们现在将代码更改过来了，再次感谢！

**Comment by HuaYZhao** [comment]
不客气
